Plugin unit tests
SpearDevs/SyliusPushNotificationsPlugin pull request #33
Opened 2023-10-19 12:21 UTC by TomaszLach2

2023-10-19 12:56 UTC, TheSylwio submitted a review, later dismissed
Major changes:
1. Add missing return types
2. Drop `/** @var TestedClassExample&MockObject */` annotation for tested (not mocked) classes.
3. Use static methods for `once()` and `never()`
4. I would rather not bypass finals. To discuss with @Codeweld

2023-10-19 12:56 UTC, TheSylwio commented on tests/Unit/ChannelContext/ChannelContextTest.php
> +    /** @var ChannelContextInterface&MockObject */
In setUp method you don't assign mock for tested class, so this line is not necessary

2023-10-20 06:31 UTC, Codeweld requested changes
In general remember to not overuse `expects` statements

2023-10-20 06:31 UTC, Codeweld commented on tests/Unit/Generator/IconPathGeneratorTest.php
> +        Assert::assertIsString($path);
Can it be something different than string? Nope, because it's the return type of the `generate` method.
Maybe we can assert that the string contains `.png`?

2023-10-20 06:31 UTC, Codeweld commented on tests/Unit/Factory/WebPushFactoryTest.php
> +        $parameterMapper->expects(self::once())
Do not overuse `expects`.
We need to answer questions:
1. Is it important for me to check whether it's called once or twice?
2. Will this change anything?

We can leave it as is, but the more redundant `expects` statements we have, the more static the code is (concreted).
This leads to the situation, that any change (even a minor one) in tests may lead to breaking tests - even if they shouldn't break because the outcome is the same.
@TheSylwio this one is also for you

2023-10-20 06:31 UTC, Codeweld commented on tests/Unit/Factory/PushNotificationHistoryFactoryTest.php
> +        Assert::assertInstanceOf(PushNotificationHistoryInterface::class, $result);
We could also verify the contents of a push title and content

2023-10-20 06:31 UTC, Codeweld commented on tests/Unit/Manager/UserSubscriptionManagerTest.php
> +    public function testHash(): void
No `Given-When-Then`.
Please verify also other test cases

2023-10-20 07:02 UTC, TomaszLach2 commented on composer.json
> +        "dg/bypass-finals": "^1.5",
Final PushResponse class that is mocked comes from an external package, so that's why is still final.

2023-10-20 07:14 UTC, TomaszLach2 commented on tests/Unit/WebPush/WebPushTest.php
> +    public function testGetTitle(): void
Unnecessary test removed.

2023-10-20 07:15 UTC, TomaszLach2 commented on tests/Unit/Factory/WebPushFactoryTest.php
> +        $parameterMapper->expects(self::once())
For now, I'm leaving it as it is.

2023-10-20 08:17 UTC, TheSylwio commented on composer.json
> +        "dg/bypass-finals": "^1.5",
I would rather use constructor for final classes directly in test than drop `final`

2023-10-20 09:05 UTC, TomaszLach2 commented on composer.json
> +        "dg/bypass-finals": "^1.5",
Ok I see. I made changes tests, the package dg/bypass-finals was uninstalled, final classes are not mocked in the tests.

2023-10-26 03:52 UTC, Codeweld requested changes

2023-10-26 03:52 UTC, Codeweld commented on tests/Unit/ChannelContext/ChannelContextTest.php
> +        $this->expectException(ChannelNotFoundException::class);
Should be in `Then` section

2023-10-26 03:52 UTC, Codeweld commented on tests/Unit/Manager/UserSubscriptionManagerTest.php
> +        //When
Given

2023-10-26 03:52 UTC, Codeweld commented on tests/Unit/Manager/UserSubscriptionManagerTest.php
> +        //Given
When

2023-10-26 09:54 UTC, Codeweld approved these changes

2023-10-26 12:44 UTC, merged