Integration test
SpearDevs/SyliusPushNotificationsPlugin pull request #34
Opened 2023-10-27 11:13 UTC by TomaszLach2

2023-11-02 04:42 UTC, Codeweld requested changes

2023-11-02 12:54 UTC, TomaszLach2 commented on tests/Integration/ChannelContext/ChannelContextTest.php
> +    public function testThrowExceptionWhenChannelCodeIsNull(): void
Unneceseary test removed.

2023-11-02 12:54 UTC, TomaszLach2 commented on tests/Integration/ChannelContext/ChannelContextTest.php
> +    public function testThrowExceptionWhenChannelIsNull(): void
Unneceseary test removed.

2023-11-02 12:54 UTC, TomaszLach2 commented on tests/Integration/Event/Admin/PushNotificationConfigurationEventSubscriberTest.php
> +    public function testUploadWithoutFile(): void
Unneceseary test removed.

2023-11-02 13:09 UTC, TomaszLach2 commented on tests/Application/config/packages/doctrine.yaml
> +            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
Yes, I am working on a test database.
https://symfony.com/doc/current/the-fast-track/en/17-tests.html#working-with-a-test-database

2023-11-02 13:12 UTC, TomaszLach2 commented on tests/Integration/Event/Admin/PushNotificationConfigurationEventSubscriberTest.php
> +        self::assertNull($configuration->getIconPath());
Unneceseary test removed.

2023-11-02 13:14 UTC, TomaszLach2 commented on tests/Application/config/services_test.yaml
> +    SpearDevs\SyliusPushNotificationsPlugin\:
I understand, this declaration is unnecessary.

2023-11-13 23:29 UTC, Codeweld approved these changes

2023-11-13 23:29 UTC, merged